name: Snyk Scanning Workflow

on: workflow_dispatch

jobs:

  execute:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert Repository Name to LowerCase
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}:nginx-testing
      - name: Donwload, Install and Initialize Snyk
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
          snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Scan container image using Snyk
        continue-on-error: true
        run: |
          snyk container monitor ghcr.io/${{ env.IMAGE_REPOSITORY }}:nginx-testing --org=${{ secrets.SNYK_ORGID }}
      - name: Scan code base using Snyk
        continue-on-error: true
        run: |
          snyk code test --org=${{ secrets.SNYK_ORGID }} 
      - name: Scan dependencies using Snyk
        continue-on-error: true
        run: |
          snyk monitor --all-projects --org=${{ secrets.SNYK_ORGID }}
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4 # Use the latest version
      #   with:
      #     name: aqua-trivy-report
      #     path: |
      #       /usr/local/bin/image-result.txt
      #       /usr/local/bin/code-result.txt
  
  # report:
  #   runs-on: ubuntu-latest
  #   needs: execute
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4 # Use the latest version
  #       with:
  #         name: aqua-trivy-report # Must match the name used during upload
  #         path: ./reports
  #     - name: Read the image report
  #       run: cat ./reports/image-result.txt
  #     - name: Read the code report
  #       run: cat ./reports/code-result.txt