name: Snyk Scanning Workflow

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert Repository Name to LowerCase
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}:nginx-testing

  snyk-terraform-scan:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Donwload, Install and Initialize Terraform CLI
        uses: ./.github/actions/terraform-cli
      - name: Donwload, Install and Initialize Snyk
        uses: ./.github/actions/snyk-cli
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}
      - name: Scan terraform files using Snyk
        continue-on-error: true
        run: |
          snyk iac test ./terraform --org=${{ secrets.SNYK_ORGID }} --report --json-file-output=terraform-vuln.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Use the latest version
        with:
          name: snyk-code-scan-report-${{ github.run_id }}
          overwrite: true
          path: |
            terraform-vuln.json

  snyk-code-scan:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Donwload, Install and Initialize Snyk
        uses: ./.github/actions/snyk-cli
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}
      - name: Scan app code using Snyk
        continue-on-error: true
        run: |
          snyk code test --org=${{ secrets.SNYK_ORGID }} --report --project-name=${{ github.repository }} --json-file-output=code-vuln.json
      - name: Scan app dependencies using Snyk
        continue-on-error: true
        run: |
          pip install -r requirements.txt
          snyk test --all-projects --org=${{ secrets.SNYK_ORGID }} --json-file-output=dependencies-vuln.json --severity-threshold=high --fail-on=all
      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Use the latest version
        with:
          name: snyk-code-scan-report-${{ github.run_id }}
          overwrite: true
          path: |
            code-vuln.json
            dependencies-vuln.json
  
  snyk-image-scan:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Convert Repository Name to LowerCase
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Donwload, Install and Initialize Snyk
        uses: ./.github/actions/snyk-cli
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}
      - name: Scan container image using Snyk
        continue-on-error: true
        run: |
          snyk container test ghcr.io/${{ env.IMAGE_REPOSITORY }}:nginx-testing --org=${{ secrets.SNYK_ORGID }} --json-file-output=image-vuln.json --severity-threshold=high --fail-on=all
      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Use the latest version
        with:
          name: snyk-image-scan-report-${{ github.run_id }}
          overwrite: true
          path: |
            image-vuln.json

  report:
    runs-on: ubuntu-latest
    needs: [snyk-code-scan, snyk-image-scan]
    steps:
      - name: Download code scan artifact
        uses: actions/download-artifact@v4 # Use the latest version
        with:
          name: snyk-code-scan-report-${{ github.run_id }} # Must match the name used during upload
      - name: Read the code report
        run: cat code-vuln.json | jq .
      - name: Read the dependencies report
        run: cat dependencies-vuln.json | jq .
      - name: Download image scan artifact
        uses: actions/download-artifact@v4 # Use the latest version
        with:
          name: snyk-image-scan-report-${{ github.run_id }} # Must match the name used during upload
      - name: Read the image report
        run: cat image-vuln.json | jq .
      - name: Read the image report
        run: cat terraform-vuln.json | jq .